name: My Test Workflow

on: 
  pull_request:
    branches: [ master ]

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2
          
        - name: Setup Node.js environment
          uses: actions/setup-node@v4.1.0

        - name: Run ESLint
          run: npm run lint
